version: '2'
services:
  # config:
  #   image: lsquared/mosquitto-config:latest
  #   volumes:
  #     - broker-config:/mosquitto/config
  #     - proxy-config:/nginx/config

  broker:
    image: lsquared/mosquitto:1.4.14
    labels:
      io.rancher.container.pull_image: always
    networks:
    - mosquitto
    restart: always
    stdin_open: true
    volumes:
      - broker-config:/srv/mosquitto/config
      - broker-data:/srv/mosquitto/data

  proxy:
    image: rancher/lb-service-haproxy
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
    networks:
      - mosquitto
    ports:
    {{- if (.Values.MQTT_PORT) }}
      - ${MQTT_PORT}:1883
    {{- end }}
    {{- if (.Values.MQTT_SSL_PORT) }}
      - ${MQTT_SSL_PORT}:8883
    {{- end }}
    {{- if (.Values.MQTT_WSS_PORT) }}
      - ${MQTT_WSS_PORT}:9883
    {{- end }}
    restart: always

volumes:
  broker-config:
  broker-data:

network:
  mosquitto:
